server:
  port: 8080
#url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Thonguyenvan96@
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    enabled: true
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: utf-8
    default-locale: en
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: newKey1996

