#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/dpshop
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Thonguyenvan96@
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    enabled: true
#    cache: false
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    defer-datasource-initialization: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  sql:
#    init:
#      mode: embedded
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#app:
#  token:
#    signingKey: newKey1996